MvcApplication.Razor/Models/Person.cs
using System.ComponentModel;

namespace MvcApplication1.Models
{
    public class Person
    {
        [DisplayName("What's your name")] public string Name { get; set; }
    }
}

MvcApplication.Razor/Controllers/CoolController.cs
using System.Web.Mvc;
using ApprovalUtilities.Asp.Mvc;
using ApprovalUtilities.SimpleLogger;
using MvcApplication1.Models;

namespace MvcApplication1.Controllers
{
    public partial class CoolController : Controller
    {
        //
        // GET: /Cool/

        public ActionResult Index()
        {
            Logger.Variable("controller", ControllerBuilder.Current.GetControllerFactory());
            return View();
        }

        [HttpPost]
        public ActionResult SaveName(Person person)
        {
            return View(person).Explicit();
        }
    }

#if DEBUG
    public partial class CoolController
    {
        public ActionResult TestName()
        {
            return MvcUtilites.CallViewResult(SaveName, new Person {Name = "Henrik"});
        }
    }
#endif
}

MvcApplication.Razor/Controllers/ExampleController.cs
using System.Web.Mvc;
using ApprovalUtilities.Asp.Mvc;
using MvcApplication1.Models;

namespace MvcApplication1.Controllers
{
    public class ExampleController : ControllerWithExplicitViews // Automatically adds the .Explicit to all views
    {
        public ActionResult Index()
        {
            return View().Explicit();
            /*
             * .Explicit()
             * is the same as
             * View("Index");
             * and allows the view to work when called from the test controller
             *
             * Note: this is not actually needed if you use the ControllerWithExplicitViews as a base class
             */
        }

        public ActionResult PageWithVerificationToken()
        {
            return View().Explicit();
        }

        [HttpPost]
        public ActionResult SaveName(Person person)
        {
            return View(person);
        }
    }
}

MvcApplication.Razor/Controllers/NonExplicitController.cs
using System.Web.Mvc;

namespace MvcApplication1.Controllers
{
    public class NonExplicitController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

MvcApplication.Razor/Views/Cool/Index.cshtml
@using MvcApplication1.Views
@model MvcApplication1.Models.Person
@{
    ViewBag.Title = "title";
    Layout = Config.DefaultLayout;
}

<div>
    @using (Html.BeginForm("SaveName", "Cool", FormMethod.Post))
    {
        <fieldset>
            <div>
                @Html.LabelFor(m => m.Name)
            </div>
            <div>
                @Html.TextBoxFor(m => m.Name)
            </div>
            <div>
                <input type="submit" value="Send"/>
            </div>
        </fieldset>
    }
</div>

MvcApplication.Razor/Views/Example/Index.cshtml
@using MvcApplication1.Views
@model MvcApplication1.Models.Person
@{
    ViewBag.Title = "title";
    Layout = Config.DefaultLayout;
}

<div>
    @using (Html.BeginForm("SaveName", "Example", FormMethod.Post))
    {
        <fieldset>
            <div>
                @Html.LabelFor(m => m.Name)
            </div>
            <div>
                @Html.TextBoxFor(m => m.Name)
            </div>
            <div>
                <input type="submit" value="Send"/>
            </div>
        </fieldset>
    }
</div>

MvcApplication.Razor/Views/Example/PageWithVerificationToken.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>Verification Token Page</title>
</head>
<body>
<div>
    @Html.AntiForgeryToken()
</div>
</body>
</html>

MvcApplication.Razor/Views/Example/SaveName.cshtml
@using MvcApplication1.Views
@model MvcApplication1.Models.Person

@{
    ViewBag.Title = "title";
    Layout = Config.DefaultLayout;
}

<p>Hello @Model.Name</p>

MvcApplication.Razor/Views/NonExplicit/Index.cshtml
@model dynamic

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>title</title>
</head>
<body>
<div>

</div>
</body>
</html>

MvcApplication.Razor/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css"/>
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>
</head>

<body>
@RenderBody()
</body>
</html>